services:
  test-alert:
    image: triargos/heartbeat-alert
    container_name: heartbeat-alert
    volumes:
      - ./packages/db/prisma/dev.db:/app/packages/db/prisma/dev.db
      - ./heartbeat.json/:/app/heartbeat.json
      - ./.env:/app/.env